FROM prestashop/prestashop:1.7

ARG MYSQLPASSWORD
ARG MYSQLHOST
ARG MYSQLPORT
ARG MYSQLDATABASE
ARG MYSQLUSER
ARG SIZE_LIMIT

ENV PRESTASHOP_DB_HOST=$MYSQLHOST:$MYSQLPORT
ENV PRESTASHOP_DB_NAME=$MYSQLDATABASE
ENV PRESTASHOP_DB_USER=$MYSQLUSER
ENV PRESTASHOP_DB_PASSWORD=$MYSQLPASSWORD
ENV PRESTASHOP_TABLE_PREFIX="PS_"

# These two directories are docker mounted volumes
RUN chown -R www-data:www-data /var/www/html
RUN chown -R www-data:www-data /var/www/html

RUN echo "ServerName 0.0.0.0" >> /etc/apache2/apache2.conf
RUN echo "DirectoryIndex index.php index.html" >> /etc/apache2/apache2.conf

# Set the maximum upload file size directly in the PHP configuration
RUN echo "upload_max_filesize = $SIZE_LIMIT" >> /usr/local/etc/php/php.ini
RUN echo "post_max_size = $SIZE_LIMIT" >> /usr/local/etc/php/php.ini

# Install mailutils to make sendmail work
RUN apt install -y \
    apt-utils \
    mailutils

CMD ["/tmp/docker_run_git.sh"]
